framework:
  messenger:
    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    # failure_transport: failed

    transports:
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        retry_strategy:
          max_retries: 3
          # milliseconds delay
          delay: 1000
          # causes the delay to be higher before each retry
          # e.g. 1 second delay, 2 seconds, 4 seconds
          multiplier: 5
